### ISSUE TITLE
Cannot find module 'crypto-js'这个怎么处理

### ISSUE THREAD

**Issue by tigerwantMISC** [linbailo/zyqinglong#14]
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'crypto-js'
Require stack:
- /ql/data/scripts/sf.swap.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/ql/data/scripts/sf.swap.js:21:794)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/data/scripts/sf.swap.js' ]
}

**Comment by linbailo** [comment]
安装依赖

> node:internal/modules/cjs/loader:1080 throw err; ^
> 
> Error: Cannot find module 'crypto-js' Require stack:
> 
> * /ql/data/scripts/sf.swap.js
>   at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
>   at Module._load (node:internal/modules/cjs/loader:922:27)
>   at Module.require (node:internal/modules/cjs/loader:1143:19)
>   at require (node:internal/modules/cjs/helpers:119:18)
>   at Object. (/ql/data/scripts/sf.swap.js:21:794)
>   at Module._compile (node:internal/modules/cjs/loader:1256:14)
>   at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
>   at Module.load (node:internal/modules/cjs/loader:1119:32)
>   at Module._load (node:internal/modules/cjs/loader:960:12)
>   at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/ql/data/scripts/sf.swap.js' ]
>   }

安装NodeJs依赖crypto-js库
