### ISSUE TITLE
滴滴打车签到错误

### ISSUE THREAD

**Issue by 4nth0nyl1MHC** [linbailo/zyqinglong#2]
变量设为
uid=xxxxx&token=xxxxx

错误信息为

--------福利金查询--------
查询失败
--------领取优惠券--------
登录失败
--------福利中心签到------
登录信息失效，请重新登录
--------天天领券签到------
登录错误
'data'
--------瓜瓜乐打卡--------
Traceback (most recent call last):
  File "/ql/data/scripts/linbailo_zyqinglong/dddc.py", line 284, in <module>
    raise e
  File "/ql/data/scripts/linbailo_zyqinglong/dddc.py", line 281, in <module>
    main(uid,token)
  File "/ql/data/scripts/linbailo_zyqinglong/dddc.py", line 46, in main
    guafen(uid,token)
  File "/ql/data/scripts/linbailo_zyqinglong/dddc.py", line 176, in guafen
    rqi = list(shuju['data']['divide_data']['divide'])
KeyError: 'divide_data'

**Comment by linbailo** [comment]
变量错了，重新获取需要的变量
