### ISSUE TITLE
mt论坛出错

### ISSUE THREAD

**Issue by soezzzz** [linbailo/zyqinglong#22]
查找到1个账号
==================================
loginhash、formhash获取失败
loginhash、formhash获取失败
Traceback (most recent call last):
  File "mt.py", line 139, in <module>
    main(username,password)
  File "mt.py", line 89, in main
    denurl = f'https://bbs.binmt.cc/member.php?mod=logging&action=login&loginsubmit=yes&handlekey=login&loginhash={loginhash}&inajax=1'
UnboundLocalError: local variable 'loginhash' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mt.py", line 146, in <module>
    pdcf = main(username,password)
  File "mt.py", line 89, in main
    denurl = f'https://bbs.binmt.cc/member.php?mod=logging&action=login&loginsubmit=yes&handlekey=login&loginhash={loginhash}&inajax=1'
UnboundLocalError: local variable 'loginhash' referenced before assignment

**Comment by linbailo** [comment]
> loginhash、formhash获取失败
> loginhash、formhash获取失败
> Traceback (most recent call last

第一第二行，获取不到
