### ISSUE TITLE
顺丰有问题了

### ISSUE THREAD

**Issue by whygong1** [linbailo/zyqinglong#25]
[21:51:01][顺丰速运]开始运行

ReferenceError: MAX_AUTH_RETRY is not defined
    at _0x14733d (/ql/data/scripts/linbailo_zyqinglong/sfsyV2.js:20:134752)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /ql/data/scripts/linbailo_zyqinglong/sfsyV2.js:20:131115

[21:51:02][顺丰速运]运行结束，共运行了0.402秒
这是怎么回事？出问题了？

**Comment by linbailo** [comment]
> [21:51:01][顺丰速运]开始运行
> 
> ReferenceError: MAX_AUTH_RETRY is not defined at _0x14733d (/ql/data/scripts/linbailo_zyqinglong/sfsyV2.js:20:134752) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async /ql/data/scripts/linbailo_zyqinglong/sfsyV2.js:20:131115
> 
> [21:51:02][顺丰速运]运行结束，共运行了0.402秒 这是怎么回事？出问题了？

重新拉库看看

**Comment by lanjingling6116** [comment]
佬哥，顺丰的抓哪个变量啊？为啥运行不了啊？

**Comment by linbailo** [comment]
> 佬哥，顺丰的抓哪个变量啊？为啥运行不了啊？

打开文件里面文件里面有详细说抓哪个

**Comment by lanjingling6116** [comment]
打开小程序或APP-我的-积分, 捉以下几种url之一,把整个url放到变量 sfsyUrl 里,多账号换行分割
https://mcs-mimp-web.sf-express.com/mcs-mimp/share/weChat/shareGiftReceiveRedirect
https://mcs-mimp-web.sf-express.com/mcs-mimp/share/app/shareRedirect
这是抓整个cookie的意思吗？写上去了运行不了，获取不到账号，变量名没写错

**Comment by linbailo** [comment]
> 打开小程序或APP-我的-积分, 捉以下几种url之一,把整个url放到变量 sfsyUrl 里,多账号换行分割 https://mcs-mimp-web.sf-express.com/mcs-mimp/share/weChat/shareGiftReceiveRedirect https://mcs-mimp-web.sf-express.com/mcs-mimp/share/app/shareRedirect 这是抓整个cookie的意思吗？写上去了运行不了，获取不到账号，变量名没写错

抓url，自己复制那个url就可以了，不是cookie

**Comment by lanjingling6116** [comment]
> > 打开小程序或APP-我的-积分, 捉以下几种url之一,把整个url放到变量 sfsyUrl 里,多账号换行分割 https://mcs-mimp-web.sf-express.com/mcs-mimp/share/weChat/shareGiftReceiveRedirect https://mcs-mimp-web.sf-express.com/mcs-mimp/share/app/shareRedirect 这是抓整个cookie的意思吗？写上去了运行不了，获取不到账号，变量名没写错
> 
> 抓url，自己复制那个url就可以了，不是cookie

谢谢老哥，懂了

**Comment by yiyandijgzhen** [comment]
老哥把那个url放哪里啊

**Comment by lanjingling6116** [comment]
> 老哥把那个url放哪里啊

在环境变量里新建，名称是sfsyUrl
值是你抓的URL

**Comment by lanjingling6116** [comment]
最新版本不是2.12吗，在哪里下载文件？

**Comment by linbailo** [comment]
> 最新版本不是2.12吗，在哪里下载文件？

重新拉库，自己就更新了

**Comment by lanjingling6116** [comment]
好的老哥，找到了已经
