### ISSUE TITLE
蜜雪冰城 卡在找到一个账号

### ISSUE THREAD

**Issue by wings110** [linbailo/zyqinglong#40]
蜜雪冰城 卡在共找到1个账号，一直这个状态

**Comment by rer-coder** [comment]
俺也一样

**Comment by liyou0000** [comment]
+1

**Comment by liuckv** [comment]
❗️蜜雪冰城, 错误!
TypeError: Cannot read properties of undefined (reading 'code')
    at UserInfo.task_signin (/arcadia/repo/mxbc.js:116:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async start (/arcadia/repo/mxbc.js:46:26)
    at async /arcadia/repo/mxbc.js:137:9
get请求失败

我是这个问题，这个能解决吗？

**Comment by 895268679long** [comment]
蜜雪冰城的号 在哪里搞
