### ISSUE TITLE
MT论坛登录失败

### ISSUE THREAD

**Issue by Gimcyz** [linbailo/zyqinglong#47]
腾讯云服务器广州的IP
日志显示为：
==================================
查找到1个账号
==================================
loginhash、formhash获取失败
loginhash、formhash获取失败
Traceback (most recent call last):
  File "/ql/data/scripts/linbailo_zyqinglong/mt.py", line 128, in <module>
    main(username,password)
  File "/ql/data/scripts/linbailo_zyqinglong/mt.py", line 78, in main
    denurl = f'https://bbs.binmt.cc/member.php?mod=logging&action=login&loginsubmit=yes&handlekey=login&loginhash={loginhash}&inajax=1'
                                                                                                                   ^^^^^^^^^
UnboundLocalError: cannot access local variable 'loginhash' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ql/data/scripts/linbailo_zyqinglong/mt.py", line 135, in <module>
    pdcf = main(username,password)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/linbailo_zyqinglong/mt.py", line 78, in main
    denurl = f'https://bbs.binmt.cc/member.php?mod=logging&action=login&loginsubmit=yes&handlekey=login&loginhash={loginhash}&inajax=1'
                                                                                                                   ^^^^^^^^^
UnboundLocalError: cannot access local variable 'loginhash' where it is not associated with a value

## 执行结束...   耗时 2 秒

**Comment by Gimcyz** [comment]
> > # 腾讯云服务器广州的IP
> > 日志显示为：
> > # 查找到1个账号
> > loginhash、formhash获取失败 loginhash、formhash获取失败 Traceback (most recent call last): File "/ql/data/scripts/linbailo_zyqinglong/mt.py", line 128, in main(username,password) File "/ql/data/scripts/linbailo_zyqinglong/mt.py", line 78, in main denurl = f'[https://bbs.binmt.cc/member.php?mod=logging&action=login&loginsubmit=yes&handlekey=login&loginhash={loginhash}&inajax=1](https://bbs.binmt.cc/member.php?mod=logging&action=login&loginsubmit=yes&handlekey=login&loginhash=%7Bloginhash%7D&inajax=1)' ^^^^^^^^^ UnboundLocalError: cannot access local variable 'loginhash' where it is not associated with a value
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last): File "/ql/data/scripts/linbailo_zyqinglong/mt.py", line 135, in pdcf = main(username,password) ^^^^^^^^^^^^^^^^^^^^^^^ File "/ql/data/scripts/linbailo_zyqinglong/mt.py", line 78, in main denurl = f'[https://bbs.binmt.cc/member.php?mod=logging&action=login&loginsubmit=yes&handlekey=login&loginhash={loginhash}&inajax=1](https://bbs.binmt.cc/member.php?mod=logging&action=login&loginsubmit=yes&handlekey=login&loginhash=%7Bloginhash%7D&inajax=1)' ^^^^^^^^^ UnboundLocalError: cannot access local variable 'loginhash' where it is not associated with a value
> > ## 执行结束... 耗时 2 秒
> 
> 腾讯云不得不给打开。建议本地挂

好吧，哈哈，我想着挂服务器上呢

**Comment by wcwq98** [comment]
我华为云 广州ip也这样
