### ISSUE TITLE
得物运行失败

### ISSUE THREAD

**Issue by Dlian-Zero** [linbailo/zyqinglong#6]
命令未添加 "now"，随机延迟 246 秒后执行

🔔得物农场, 开始!
共找到1个账号

============ 当前版本：0.0.1 📌 最新版本：0.0.1 ============
获取首账号助力码
😻🌾🌸👽🌴💢💯

================== 奖励 ==================

账号[1]  查询奖励[成功] [迪士尼耳机] 当前等级[10]
post请求失败

❗️得物农场, 错误!

TypeError: Cannot read properties of undefined (reading 'code')
    at UserInfo.task_signIn (/ql/data/scripts/dwxysl.js:479:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async start (/ql/data/scripts/dwxysl.js:66:22)
    at async /ql/data/scripts/dwxysl.js:756:9

------------------ 执行任务 ------------------

账号[1]  正在尝试完成所有任务
账号[1]  检测未到达任务时间节点,不执行该任务
账号[1]  时间段领水
账号[1]  [服装开学季水滴大放送] --- 执行
账号[1]  [综合会场开学季水滴大放送] --- 执行
账号[1]  [新人折扣会场水滴大放送] --- 执行
账号[1]  [完成一次签到] --- 执行
post请求失败

❗️得物农场, 错误!

TypeError: Cannot read properties of undefined (reading 'code')
    at UserInfo.task_signIn2 (/ql/data/scripts/dwxysl.js:508:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UserInfo.task_false (/ql/data/scripts/dwxysl.js:266:21)
    at async start (/ql/data/scripts/dwxysl.js:73:22)
    at async /ql/data/scripts/dwxysl.js:756:9
账号[1]  [从桌面组件访问许愿树] --- 执行
账号[1]  [去0元抽奖参与抽游戏皮肤] --- 执行
账号[1]  [参与1次上上签活动] --- 执行
账号[1]  [逛逛国潮夏季专场] --- 执行
账号[1]  [浏览美妆会场15s] --- 执行

------------------ 浇水 ------------------

post请求失败

❗️得物农场, 错误!

TypeError: Cannot read properties of undefined (reading 'code')
    at UserInfo.user_info (/ql/data/scripts/dwxysl.js:195:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async start (/ql/data/scripts/dwxysl.js:80:22)
    at async /ql/data/scripts/dwxysl.js:756:9

------------------ 领取完成任务奖励 ------------------

账号[1]  领取累计任务奖励
post请求失败

❗️得物农场, 错误!

TypeError: Cannot read properties of undefined (reading 'code')
    at UserInfo.task_extra (/ql/data/scripts/dwxysl.js:615:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UserInfo.task_true (/ql/data/scripts/dwxysl.js:370:17)
    at async start (/ql/data/scripts/dwxysl.js:86:22)
    at async /ql/data/scripts/dwxysl.js:756:9
账号[1]  领取累计任务奖励
post请求失败

❗️得物农场, 错误!

TypeError: Cannot read properties of undefined (reading 'code')
    at UserInfo.task_extra (/ql/data/scripts/dwxysl.js:615:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UserInfo.task_true (/ql/data/scripts/dwxysl.js:370:17)
    at async start (/ql/data/scripts/dwxysl.js:86:22)
    at async /ql/data/scripts/dwxysl.js:756:9
账号[1]  领取累计任务奖励
post请求失败

❗️得物农场, 错误!

TypeError: Cannot read properties of undefined (reading 'code')
    at UserInfo.task_extra (/ql/data/scripts/dwxysl.js:615:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UserInfo.task_true (/ql/data/scripts/dwxysl.js:370:17)
    at async start (/ql/data/scripts/dwxysl.js:86:22)
    at async /ql/data/scripts/dwxysl.js:756:9
post请求失败

❗️得物农场, 错误!

TypeError: Cannot read properties of undefined (reading 'code')
    at UserInfo.task_watering_reward (/ql/data/scripts/dwxysl.js:558:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UserInfo.task_true (/ql/data/scripts/dwxysl.js:375:9)
    at async start (/ql/data/scripts/dwxysl.js:86:22)
    at async /ql/data/scripts/dwxysl.js:756:9
账号[1]  气泡水滴已满,今日可领取 --- [10]g
post请求失败

❗️得物农场, 错误!

TypeError: Cannot read properties of undefined (reading 'code')
    at UserInfo.droplet_extra_receive (/ql/data/scripts/dwxysl.js:665:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UserInfo.droplet_extra_info (/ql/data/scripts/dwxysl.js:643:21)
    at async UserInfo.task_true (/ql/data/scripts/dwxysl.js:376:9)
    at async start (/ql/data/scripts/dwxysl.js:86:22)
    at async /ql/data/scripts/dwxysl.js:756:9
账号[1]  领取小木桶积攒水滴:原因未知
post请求失败

❗️得物农场, 错误!

TypeError: Cannot read properties of undefined (reading 'code')
    at UserInfo.task_receive (/ql/data/scripts/dwxysl.js:590:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UserInfo.task_true (/ql/data/scripts/dwxysl.js:384:17)
    at async start (/ql/data/scripts/dwxysl.js:86:22)
    at async /ql/data/scripts/dwxysl.js:756:9
post请求失败

❗️得物农场, 错误!

TypeError: Cannot read properties of undefined (reading 'code')
    at UserInfo.task_receive (/ql/data/scripts/dwxysl.js:590:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UserInfo.task_true (/ql/data/scripts/dwxysl.js:384:17)
    at async start (/ql/data/scripts/dwxysl.js:86:22)
    at async /ql/data/scripts/dwxysl.js:756:9
post请求失败

❗️得物农场, 错误!

TypeError: Cannot read properties of undefined (reading 'code')
    at UserInfo.task_receive (/ql/data/scripts/dwxysl.js:590:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UserInfo.task_true (/ql/data/scripts/dwxysl.js:384:17)
    at async start (/ql/data/scripts/dwxysl.js:86:22)
    at async /ql/data/scripts/dwxysl.js:756:9
post请求失败

❗️得物农场, 错误!

TypeError: Cannot read properties of undefined (reading 'code')
    at UserInfo.task_receive (/ql/data/scripts/dwxysl.js:590:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UserInfo.task_true (/ql/data/scripts/dwxysl.js:384:17)
    at async start (/ql/data/scripts/dwxysl.js:86:22)
    at async /ql/data/scripts/dwxysl.js:756:9
post请求失败

❗️得物农场, 错误!

TypeError: Cannot read properties of undefined (reading 'code')
    at UserInfo.task_receive (/ql/data/scripts/dwxysl.js:590:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UserInfo.task_true (/ql/data/scripts/dwxysl.js:384:17)
    at async start (/ql/data/scripts/dwxysl.js:86:22)
    at async /ql/data/scripts/dwxysl.js:756:9
post请求失败

❗️得物农场, 错误!

TypeError: Cannot read properties of undefined (reading 'code')
    at UserInfo.task_receive (/ql/data/scripts/dwxysl.js:590:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UserInfo.task_true (/ql/data/scripts/dwxysl.js:384:17)
    at async start (/ql/data/scripts/dwxysl.js:86:22)
    at async /ql/data/scripts/dwxysl.js:756:9
post请求失败

❗️得物农场, 错误!

TypeError: Cannot read properties of undefined (reading 'code')
    at UserInfo.task_receive (/ql/data/scripts/dwxysl.js:590:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UserInfo.task_true (/ql/data/scripts/dwxysl.js:384:17)
    at async start (/ql/data/scripts/dwxysl.js:86:22)
    at async /ql/data/scripts/dwxysl.js:756:9
post请求失败

❗️得物农场, 错误!

TypeError: Cannot read properties of undefined (reading 'code')
    at UserInfo.task_receive (/ql/data/scripts/dwxysl.js:590:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UserInfo.task_true (/ql/data/scripts/dwxysl.js:384:17)
    at async start (/ql/data/scripts/dwxysl.js:86:22)
    at async /ql/data/scripts/dwxysl.js:756:9
post请求失败

❗️得物农场, 错误!

TypeError: Cannot read properties of undefined (reading 'code')
    at UserInfo.task_receive (/ql/data/scripts/dwxysl.js:590:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UserInfo.task_true (/ql/data/scripts/dwxysl.js:384:17)
    at async start (/ql/data/scripts/dwxysl.js:86:22)
    at async /ql/data/scripts/dwxysl.js:756:9
post请求失败

❗️得物农场, 错误!

TypeError: Cannot read properties of undefined (reading 'code')
    at UserInfo.task_receive (/ql/data/scripts/dwxysl.js:590:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UserInfo.task_true (/ql/data/scripts/dwxysl.js:384:17)
    at async start (/ql/data/scripts/dwxysl.js:86:22)
    at async /ql/data/scripts/dwxysl.js:756:9
post请求失败

❗️得物农场, 错误!

TypeError: Cannot read properties of undefined (reading 'code')
    at UserInfo.task_receive (/ql/data/scripts/dwxysl.js:590:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UserInfo.task_true (/ql/data/scripts/dwxysl.js:384:17)
    at async start (/ql/data/scripts/dwxysl.js:86:22)
    at async /ql/data/scripts/dwxysl.js:756:9
post请求失败

❗️得物农场, 错误!

TypeError: Cannot read properties of undefined (reading 'code')
    at UserInfo.task_receive (/ql/data/scripts/dwxysl.js:590:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UserInfo.task_true (/ql/data/scripts/dwxysl.js:384:17)
    at async start (/ql/data/scripts/dwxysl.js:86:22)
    at async /ql/data/scripts/dwxysl.js:756:9
post请求失败

❗️得物农场, 错误!

TypeError: Cannot read properties of undefined (reading 'code')
    at UserInfo.task_receive (/ql/data/scripts/dwxysl.js:590:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UserInfo.task_true (/ql/data/scripts/dwxysl.js:384:17)
    at async start (/ql/data/scripts/dwxysl.js:86:22)
    at async /ql/data/scripts/dwxysl.js:756:9

------------------- [进度] -------------------

账号[1]  [XXXXX] 成熟进度 --- [5344/12000g]
成员ID:@all企业微信应用消息发送通知消息成功🎉。

🔔得物农场, 结束! 🕛 125.04 秒

**Comment by hitonqlj** [comment]
我用的是安卓vmos，我是这样改的：

**修改自定义变量区**
//---------------------- 自定义变量区域 -----------------------------------
let ua = 'duapp/5.21.1(android;7.1.2)'
let deviceTrait = 'NX701J'
let channel = 'myapp'
let UserAgent = 'Mozilla/5.0 (Linux; Android 7.1.2; NX701J Build/N2G47H; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/81.0.4044.117 Mobile Safari/537.36/duapp/5.21.1(android;7.1.2)'  //---------------------------------------------------------

**然后和楼上一样，在headersPost和headersGet中添加了一堆参数。**
我不是专业的，不太懂到底缺啥，反正都写上去了，就正常了。
记得要把下面XXXXXXX部分替换成抓包拿到的值

this.headersPost = {
            Host: 'app.dewu.com',
            'Connection': 'keep-alive',
            'x-auth-token': "Bearer " + this.XAToken,
            'Content-Type': 'application/json',
            'ua': ua,
            'deviceTrait': deviceTrait,
            'channel': channel,
            'SK': this.SK,
            'shumeiId': this.shumeiId,
            //'uuid': this.uuid,
            'deviceId': this.deviceId,
            'User-Agent': UserAgent,
            'platform': 'h5',
            'isProxy': '0',
            'duToken': 'XXXXXXXXXXXXXXXXXX',
            'emu': '0',
            'cookieToken': 'XXXXXXXXXXXXXXXXXXXXX',
            'isRoot': '0',
            'appid': 'h5',
            'appVersion': '5.21.1',
            'Accept': '*/*',
            'Origin': 'https://cdn-m.dewu.com',
            'X-Requested-With': 'com.shizhuang.duapp',
            'Sec-Fetch-Site': 'same-site',
            'Sec-Fetch-Mode': 'cors',
            'Sec-Fetch-Dest': 'empty',
            'Referer': 'https://cdn-m.dewu.com/h5-growth/wish-tree?navControl=1&source=sousuo03',
            'Accept-Encoding': 'gzip, deflate',
            'Accept-Language': 'zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7',
            'Cookie': 'duToken=XXXXXXXXXXXXXXXXX'
        };
        this.headersGet = {
            Host: 'app.dewu.com',
            'Connection': 'keep-alive',
            'x-auth-token': "Bearer " + this.XAToken,
            'ua': ua,
            'deviceTrait': deviceTrait,
            'channel': channel,
            'SK': this.SK,
            'shumeiId': this.shumeiId,
            //'uuid': this.uuid,
            'deviceId': this.deviceId,
            'User-Agent': UserAgent,
            'platform': 'h5',
            'isProxy': '0',
            'duToken': 'XXXXXXXXXXXXXXX',
            'emu': '0',
            'cookieToken': 'XXXXXXXXXXXXX',
            'isRoot': '0',
            'appid': 'h5',
            'appVersion': '5.21.1',
            'Accept': '*/*',
            'Origin': 'https://cdn-m.dewu.com',
            'X-Requested-With': 'com.shizhuang.duapp',
            'Sec-Fetch-Site': 'same-site',
            'Sec-Fetch-Mode': 'cors',
            'Sec-Fetch-Dest': 'empty',
            'Referer': 'https://cdn-m.dewu.com/h5-growth/wish-tree?navControl=1&source=sousuo03',
            'Accept-Encoding': 'gzip, deflate',
            'Accept-Language': 'zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7',
            'Cookie': 'duToken=XXXXXXXXXXXXXXXXX'
        }

**Comment by chenjuefei** [comment]
还是不行，以上的办法都试过了。

**Comment by Dlian-Zero** [comment]
> 还是不行，以上的办法都试过了。

得物加了验证码，这个脚本运行不了了，我用其他的，得过一次验证码才可以运行
