### ISSUE TITLE
蜜雪冰城运行报错

### ISSUE THREAD

**Issue by tigerwantMISC** [linbailo/zyqinglong#8]
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'jsrsasign'
Require stack:
- /ql/scripts/mxbc.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/ql/scripts/mxbc.js:165:10)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/scripts/mxbc.js' ]

**Comment by linbailo** [comment]
> node:internal/modules/cjs/loader:936 throw err; ^
> 
> Error: Cannot find module 'jsrsasign' Require stack:
> 
> * /ql/scripts/mxbc.js
>   at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>   at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>   at Module.require (node:internal/modules/cjs/loader:1005:19)
>   at require (node:internal/modules/cjs/helpers:102:18)
>   at Object. (/ql/scripts/mxbc.js:165:10)
>   at Module._compile (node:internal/modules/cjs/loader:1101:14)
>   at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
>   at Module.load (node:internal/modules/cjs/loader:981:32)
>   at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>   at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/ql/scripts/mxbc.js' ]

安装库 jsrsasign
