### ISSUE TITLE
MT论坛签到报错

### ISSUE THREAD

**Issue by yaowans** [linbailo/zyqinglong#85]
==================================
查找到1个账号
==================================
loginhash、formhash获取失败
loginhash、formhash获取失败
Traceback (most recent call last):
  File "/ql/data/scripts/yangmao/mt.py", line 129, in <module>
    main(username,password)
  File "/ql/data/scripts/yangmao/mt.py", line 79, in main
    denurl = f'https://bbs.binmt.cc/member.php?mod=logging&action=login&loginsubmit=yes&handlekey=login&loginhash={loginhash}&inajax=1'
                                                                                                                   ^^^^^^^^^
UnboundLocalError: cannot access local variable 'loginhash' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ql/data/scripts/yangmao/mt.py", line 136, in <module>
    pdcf = main(username,password)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/yangmao/mt.py", line 79, in main
    denurl = f'https://bbs.binmt.cc/member.php?mod=logging&action=login&loginsubmit=yes&handlekey=login&loginhash={loginhash}&inajax=1'
                                                                                                                   ^^^^^^^^^
UnboundLocalError: cannot access local variable 'loginhash' where it is not associated with a value

**Comment by zhangziran** [comment]
同样的问题

**Comment by hhd66624** [comment]
解决了吗？
